---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-6.6

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[eol-sensu-wrapper::default]
    attributes:
